modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="ftgu"
version="${file.jarVersion}"
displayName="From the Ground Up"
logoFile="ftgu.png"
credits=""
authors="Bluperman949"
description='''
'''
[[dependencies.ftgu]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ftgu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ftgu]]
    modId="jei"
    mandatory=true
    versionRange="[7.7.1.0,)"
    ordering="NONE"
    side="BOTH"